### ISSUE TITLE
How to setup with supabase cli?

### ISSUE THREAD

**Issue by simpros** [usebasejump/supabase-test-helpers#14]
Hi,

I wanted to use the tests with the supabase cli for now on my local machine but I am struggling hard to get dbdev running. Is this package working on supabase cli projects locally? Should i install it in the seed.sql? I am having a bit of a hard time to understand that first step, but I would love to use it :) Thx for any help.

**Comment by probablykabari** [comment]
dbdev is OK to go into your very first migration file or the seed file. Here is one I have in a project:

```sql
/*---------------------
---- install dbdev ----
----------------------
see: https://github.com/supabase/dbdev
Requires:
  - pg_tle: https://github.com/aws/pg_tle
  - pgsql-http: https://github.com/pramsey/pgsql-http
*/
create extension if not exists pgtap with schema extensions;
create extension if not exists http with schema extensions;
create extension if not exists pg_tle with schema extensions;
select pgtle.uninstall_extension_if_exists('supabase-dbdev');
drop extension if exists "supabase-dbdev";
select
    pgtle.install_extension(
        'supabase-dbdev',
        resp.contents ->> 'version',
        'PostgreSQL package manager',
        resp.contents ->> 'sql'
    )
from http(
    (
        'GET',
        'https://api.database.dev/rest/v1/'
        || 'package_versions?select=sql,version'
        || '&package_name=eq.supabase-dbdev'
        || '&order=version.desc'
        || '&limit=1',
        array[
            ('apiKey', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtdXB0cHBsZnZpaWZyYndtbXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODAxMDczNzIsImV4cCI6MTk5NTY4MzM3Mn0.z2CN0mvO2No8wSi46Gw59DFGCTJrzM0AQKsu_5k134s')::http_header
        ],
        null,
        null
    )
) x,
lateral (
    select
        ((row_to_json(x) -> 'content') #>> '{}')::json -> 0
) resp(contents);

-- Intall dbdev
create extension "supabase-dbdev";
select dbdev.install('supabase-dbdev');
drop extension if exists "supabase-dbdev";
create extension "supabase-dbdev";

-- install supabase-test-helpers
select dbdev.install('basejump-supabase_test_helpers');
drop extension if exists "basejump-supabase_test_helpers";
create extension "basejump-supabase_test_helpers";
```


Some examples are in the author's other repo here: https://github.com/usebasejump/basejump/tree/main
Also, [this is the project](https://github.com/probablykabari/bandit-bocce) that I'll be publishing in a week or so that would serve as another example of using tools like this, which may be good to follow as well.

**Comment by probablykabari** [comment]
@simpros in that case you may need to put it in a separate sql file, then write a script that runs the `db reset` cli command  then `psql` to run that sql in the database.

**Comment by tiniscule** [comment]
I've seen this happen if you're trying to put the installer in the seed file - for some reason those seem to run _before_ supabase has fully initialized the database.  The docs have also been updated recently at database.dev, so I'd make sure you're running the latest there.  I'm going to close this for now since so much has changed on the dbdev side since it was raised, but let me know if you hit it again!
