### ISSUE TITLE
ERROR:  stack depth limit exceeded

### ISSUE THREAD

**Issue by OnCoreStudios** [usebasejump/supabase-test-helpers#20]
Hi,

First of all, thanks for this test suite! It is just what I've been looking for! I've been able to implement several RLS unit tests with this package :)

However, I ran into an issue when using a plpgsql function in a RLS policy and I'm not 100% sure it isn't my local setup.

My setup is as follows:

Policy - 
```
CREATE OR REPLACE FUNCTION public.is_in_same_game(player_id uuid, other_player_id uuid)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1
        FROM players p1
        INNER JOIN players p2 ON p1.game_id = p2.game_id
        WHERE p1.id = player_id
        AND p2.id = other_player_id
        AND p1.game_id IS NOT NULL
    );
END;
$$ LANGUAGE plpgsql;


CREATE POLICY "Account viewer can view another's account if in same game"
on "public"."accounts"
as permissive
for select
to authenticated
using (
    is_in_same_game(auth.uid(), id)
);
```

Test - 
```
BEGIN
;

CREATE EXTENSION "basejump-supabase_test_helpers";

SELECT
    plan(7);

-- 11); -- 2);
-- Setup
SELECT
    tests.create_supabase_user('user1', 'john@example.com');

SELECT
    tests.create_supabase_user('user2', 'jane@example.com');

-----------
-- Acting as account owner
-----------
SELECT
    tests.authenticate_as('user1');

-- insert an account
SELECT
    results_eq(
        $$
        INSERT INTO
            PUBLIC .accounts (id, username, avatar_url, is_pro, email)
        VALUES
            (
                tests.get_supabase_uid('user1'),
                'user1',
                'some avatar url',
                FALSE,
                'john@example.com'
            ) RETURNING id $$,
            $$
        VALUES
            (tests.get_supabase_uid('user1')) $$,
            'authenticated users can insert their account'
    );

-- owner can view their own account
SELECT
    results_eq(
        $$
        SELECT
            id,
            username,
            avatar_url,
            is_pro,
            email
        FROM
            accounts
        LIMIT
            1 $$, $$
        VALUES
            (
                tests.get_supabase_uid('user1'),
                'user1',
                'some avatar url',
                FALSE,
                'john@example.com'
            ) $$,
            'Account owners can view their own account'
    );

-- owner can update the account
SELECT
    results_eq(
        $$
        UPDATE
            accounts
        SET
            avatar_url = 'Avatar updated' RETURNING avatar_url $$,
            $$
        VALUES
            ('Avatar updated') $$,
            'Account owners can update their own accounts'
    );

-- account owners cannot delete the account
SELECT
    is_empty(
        $$
        DELETE FROM
            accounts RETURNING 1 $$,
            'Account owners cannot delete posts'
    );

----------
-- Acting as account viewer
----------
SELECT
    tests.authenticate_as('user2');

-- account viewer cannot view another account if not within the same game
SELECT
    is_empty(
        $$
        SELECT
            *
        FROM
            accounts $$,
            'Account viewer cannot view other accounts not in the same game'
    );

-- account viewer cannot update the account
SELECT
    is_empty(
        $$
        UPDATE
            accounts
        SET
            avatar_url = 'Account updated by viewer' RETURNING avatar_url $$,
            'Account viewers cannot update accounts'
    );

-- account viewer cannot delete the account
SELECT
    is_empty(
        $$
        DELETE FROM
            accounts RETURNING 1 $$,
            'Account viewers cannot delete accounts'
    );

-- account viewer can view the account if in same game
-- example game for shared game account view test
INSERT INTO
    games (
        game_name,
        player_user_ids,
        host_user_id,
        min_players,
        max_players,
        game_mode,
        is_nsfw,
        customizations,
        story_option,
        game_status
    )
VALUES
    (
        'test_game',
        ARRAY [ tests.get_supabase_uid('user1'),
        tests.get_supabase_uid('user2') ],
        tests.get_supabase_uid('user2'),
        7,
        12,
        'GameMode.Competitive',
        TRUE,
        ARRAY [ '' ],
        'StoryOption.StorylineSheet',
        'GameStatus.inLobby'
    );

INSERT INTO
    players (id, NAME, game_id)
VALUES
    (
        tests.get_supabase_uid('user1'),
        'John',
        (
            SELECT
                id
            FROM
                games
            LIMIT
                1
        )
    ), (
        tests.get_supabase_uid('user2'), 'Jane', (
            SELECT
                id
            FROM
                games
            LIMIT
                1
        )
    );


SELECT
    results_eq(
        $$
        SELECT
            id,
            username,
            avatar_url,
            is_pro,
            email
        FROM
            accounts
        LIMIT
            1 $$, $$
        VALUES
            (
                tests.get_supabase_uid('user1'),
                'user1',
                'some avatar url',
                FALSE,
                'john@example.com'
            ) $$,
            'Account viewers can view other accounts in same game.'
    );

SELECT
    *
FROM
    finish();

ROLLBACK;
```

Locally, I get infinite recursion

```
psql:database/accounts_policies.test.sql:227: ERROR:  stack depth limit exceeded
HINT:  Increase the configuration parameter "max_stack_depth" (currently 2048kB), after ensuring the platform's stack depth limit is adequate.
CONTEXT:  SQL expression "EXISTS (
        SELECT 1
        FROM players p1
        INNER JOIN players p2 ON p1.game_id = p2.game_id
        WHERE p1.id = player_id
        AND p2.id = other_player_id
        AND p1.game_id IS NOT NULL
    )"
PL/pgSQL function is_in_same_game(uuid,uuid) line 3 at RETURN
SQL expression "EXISTS (
        SELECT 1
        FROM players p1
        INNER JOIN players p2 ON p1.game_id = p2.game_id
        WHERE p1.id = player_id
        AND p2.id = other_player_id
        AND p1.game_id IS NOT NULL
    )"
PL/pgSQL function is_in_same_game(uuid,uuid) line 3 at RETURN
...
Test Summary Report
-------------------
./database/accounts_policies.test.sql (Wstat: 768 (exited 3) Tests: 7 Failed: 0)
  Non-zero exit status: 3
```

The test that the overflow happens on is the last one, `'Account viewers can view other accounts in same game.'`. This is due to the `is_in_same_game` function being invoked on that test. The expect result is included in the test.

I tested statements on the `players` table using the Supabase SQL Editor that were failing locally in the unit test and it succeeded without any issues.

This might be a pgtap issue but I thought I'd just check here in case this is a known issue or can be reproduced. I saw in one of the other issues that the function language was sql and not plpgsql. Not sure if that makes a difference. Any help/insights would be appreciated! @tiniscule @probablykabari @gtarsia  @isaacharrisholt @0xBigBoss 🙏

**Comment by probablykabari** [comment]
@OnCoreStudios your `is_in_same_game` function should be defined with `security definer` if you are using it in RLS. For good measure, I typically put functions like this in a schema that is not accessible from the supabase api.

**Comment by OnCoreStudios** [comment]
> @OnCoreStudios your `is_in_same_game` function should be defined with `security definer` if you are using it in RLS. 

Thanks for the reply @probablykabari!

I am admittedly both a postgres and supabase noob so I read up a bit on `security definer`, schemas, etc.

Most notably,

- https://supabase.com/docs/guides/auth/row-level-security#using-security-definer-functions
- https://www.cybertec-postgresql.com/en/abusing-security-definer-functions/
- https://www.postgresql.org/docs/current/sql-createfunction.html#SQL-CREATEFUNCTION-SECURITY

I believe what I want to do is create a new schema, migrate everything in public over to that schema, authorize nearly everything including invoking the functions to the authenticated role, and add the security definer attribute to the function with the search path being the schema followed by pg_temp.

Is this correct?

> For good measure, I typically put functions like this in a schema that is not accessible from the supabase api.

Could you elaborate on what the supabase api that'd be accessible is? Is utilities like `auth.id()`. If so, I should be good, right? Anything I should do in particular to limit access to the supabase api?

Thanks again and please educate me anywhere you see 😄

**Comment by probablykabari** [comment]
It's a bit out of scope for this discussion but 'll try to point you in the right direction.

> I believe what I want to do is create a new schema, migrate everything in public over to that schema, authorize nearly everything including invoking the functions to the authenticated role, and add the security definer attribute to the function with the search path being the schema followed by pg_temp.

Not quite. First up is to understand the `public` schema in Postgres, and in Supabase. This schema is default where everything goes, and every user has access to _everything_ in it. In addition, with Supabase this is the schema that defines what goes into your API. [see here](https://supabase.com/docs/guides/api/using-custom-schemas). The `auth.id()` function is on the `auth` schema. For

For _tables_, you can protect data by using RLS policies. For _functions_, all _user defined_ functions are callable by the supabase API as well, the same as by any user. Nothing wrong with some of those functions being `security definer` as long as they are safe. [For example](https://github.com/graphile/starter/blob/89a876a7ac25a5a89136409ca53acc9d7578bc8d/%40app/db/migrations/committed/000001.sql#L661), a function that does required checks within the function definition.

###### A note on `search_path`

You don't need to set your own schemas in `set search_path`, the default setting already has the schema you're in. In Supabase, because it is based around `public` you may see their docs use `set search_path public` when a function is defined in _another schema_ so that it will reference your tables in there first. This is just because you can have the same name of something in different schemas (for example, I may have the table `private.members` in`private` schema, and a view called `public.members` in `public` schema). It's something you can ignore if not terribly familiar with the concept. If you need to add it, you'll get a friendly pg error about the table/etc not being found when you run your function :)

#### With Regard to Tables in Supabase
For tables that do not contain public data, I simply remove privileges from the `anon` user on them, and use RLS functions, views, lookup functions for everything protected. 

#### With Regard to RLS Functions and `security definer`

The reason much of the time you want/need an RLS function to be `security definer` is that the function itself should bypass other RLS policies in order to see row data, otherwise you can easily get an infinite loop if the function is referencing data the default user does no have access to. all but the simplest RLS functions that don't reference any tables would fall under this category. I _always_ put those in a private schema so that they are not callable from the API.


#### Additional reading:

The library, postgraphile, is an excellent base for designing APIs based on postgresql databases and the information throughout their site and tutorials is very much in line with how to think about supabase (which basically does the same thing). In the case of their examples. I usually follow this pattern but skip using "app_public" for tables and only put private functions there. 

- https://postgraphile.org/postgraphile/current/required-knowledge
- https://postgraphile.org/postgraphile/current/postgresql-schema-design

**Comment by OnCoreStudios** [comment]
Thanks a bunch @probablykabari!! :) This is great and I think I'm following what you're saying! Sorry for the delayed response, just coming back to this today!

After reading up more, I'm doing `LANGUAGE plpgsql stable security definer set search_path to public, pg_temp;` and it seems to work fine! I think my function is safe now since I revoked `CREATE` permissions in `public` for everyone except `postgres` and `service_role`, added `stable` to the function, set the search path accordingly, and move the function to a custom schema that isn't exposed on the supabase api.

Everything makes a lot more sense now and those were some great resources you linked to!

One additional thing I was wondering from a security perspective is if it makes sense to expose a different custom schema to use instead of public. This might make the endpoint discoverability of the endpoint more difficult as they may just try the public endpoint regardless. That said, maybe discovering the expose endpoint is really easy so this is irrelevant. What are your thoughts on this?

Thanks again!

**Comment by probablykabari** [comment]
For Supabase specifically it isn't necessary. I forgot to add, the docs for PostgREST would be helpful as well, because Supabase is basically a host version of that tool. Public is ok in supabase because they specifically install everything (extensions/etc) in a separate schema, and it was designed with using public in mind. you don't gain anything by using a separate schema as the default with them, you can just change the default schema to a different one in the settings or even add multiple schemas (like the graphql schema that is provided). I would recommend focusing more on writing sound RLS policies than working around what they've already provided, which is a framework to provide data access securely in tandem with sound RLS policies.

Personally, I handle insert/update by writing functions anyway because I typically need to write to more than a single table in an insert. Think about it like you are writing a route in a REST framework. You will likely need security definer functions exposed for this, because, for example, you'll often need to insert a row into a main table _and_ a join table after that (which is done in a transaction and thus handled by the function, rather than trying this in the client). So in that case you wouldn't have blocked the join table insert via RLS anyway, and the only way to prevent writes to the _joined_ table would be to check some other permission (ie, checking an account type table before allowing a new row in a feature table).

**Comment by OnCoreStudios** [comment]
Thanks again! You give great advice and information @probablykabari :)

I've locked down all of my tables behind RLS, used privileges to revoke all access except for the CLS that is needed for a user, and added functions with security definer safely to do everything else!

Upon further reading, I saw supabase rpcs and thought risk-wise, that'd be much safer than expose other rows via the initial function. Maybe either is fine but this feels much easier to maintain as well.

To top it all off, I have pgtap tests using supabase test helpers for the most sensitive table now, have a good foundation to launch from, learned quite a bit about postgres and supabase, and have a better design! I can already think of one place where a transaction will be helpful ;)

Thanks @probablykabari, you rock!

**Comment by tiniscule** [comment]
Agreed!  @probablykabari any interest in helping out as a maintainer for the test helpers?

**Comment by isaacharrisholt** [comment]
I'm just gonna chime in with my two cents here too, since I was so generously tagged in the issue ;)

This is just general RLS advice, so feel free to ignore.

If you're gonna rely on RLS for security (which we currently do, but might not for long), you're probably gonna end up writing a _lot_ of RLS policies, and lots of your RLS policies will start repeating each other.

For example, in our codebase, we have a table called `unit` representing a property (e.g. an apartment, house, etc.). Each `unit` can have many `property_valuation`s, many `monthly_rent` records, many `monthly_service_charge` records, etc.

We also have two different user types - `resident`s and `provider`s (institutional landlords, effectively). We used to have policies like:

- `resident can read units they live in`
- `provider user can read units they own`
- etc.

But, you'll start running into performance issues when you start adding more and more policies to a table. I remember discussing this with @tiniscule on Twitter. What we did to combat this was to combine our RLS policies, so we'd have something like `can read unit` which was basically an `or` of all the policies we'd had before. This reduced it down to one RLS policy per table per CRUD op, which made a massive difference (some queries went from 5.5 _seconds_ to 2 _milliseconds_).

Generally, in our app, anyone who can see a `unit` should also be able to see associated valuations, rent, etc. Because of this, we started turning all our RLS policies into security definer functions, e.g. `can_read_unit_using(bigint unit_id)`, `can_update_unit_using`, `can_update_unit_with_check`.

That way, our `property_valuation` RLS policy just had to use the unit read function. This ended up also being _really_ slow eventually because the query optimiser didn't really do well with having loads of functions. What I ended up doing was writing factory functions for RLS policies that would take in code for a boolean condition, then create an RLS policy using that directly, as well as a function that I could use in other RLS policies for composability.

Here are the results of that optimisation: https://twitter.com/IsaacHarrisHolt/status/1728465485102977282

<details>
<summary>And here are the functions that create the policies</summary>

```sql
create or replace procedure
    rls.create_rls_select_policy(
        schema_name text,
        table_name text,
        using_expression text,
        column_list text[] = '{"id"}'
    )
language plpgsql
as $$
declare
  policy_name text;
begin
  -- Create ID return function
  execute format(
    $function$ 
    create or replace function rls.can_read_%I_using()
    returns setof bigint[]
    security definer
    language sql
    as $q$
        select ARRAY[%s]::bigint[]
        from %I.%I
        where (%s)
    $q$;
    $function$,
    table_name,
    array_to_string(column_list, ','),
    schema_name,
    table_name,
    using_expression
  );

  -- Create policy
  policy_name := format('select: %s.%s', schema_name, table_name);
  execute format(
    'drop policy if exists %I on %I.%I',
    policy_name,
    schema_name,
    table_name
  );
  execute format(
    $policy$
    create policy %I
    on %I.%I
    for select
    to authenticated
    using (%s)
    $policy$,
    policy_name,
    schema_name,
    table_name,
    using_expression
  );
end;
$$
;

create or replace procedure
    rls.create_rls_insert_policy(
        schema_name text,
        table_name text,
        with_check_expression text
    )
language plpgsql
as $$
declare
  policy_name text;
begin
  -- Create policy
  policy_name := format('insert: %s.%s', schema_name, table_name);
  execute format(
    'drop policy if exists %I on %I.%I',
    policy_name,
    schema_name,
    table_name
  );
  execute format(
    $policy$
    create policy %I
    on %I.%I
    for insert
    to authenticated
    with check (%s)
    $policy$,
    policy_name,
    schema_name,
    table_name,
    with_check_expression
  );
end;
$$
;

create or replace procedure
    rls.create_rls_update_policy(
        schema_name text,
        table_name text,
        using_expression text,
        with_check_expression text,
        column_list text[] default array['id']
    )
language plpgsql
as $$
declare
  policy_name text;
begin
  -- Create ID return function
  execute format(
    $function$ 
    create or replace function rls.can_update_%I_using()
    returns setof bigint[]
    security definer
    language sql
    as $q$
        select ARRAY[%s]::bigint[]
        from %I.%I
        where (%s)
    $q$;
    $function$,
    table_name,
    array_to_string(column_list, ','),
    schema_name,
    table_name,
    using_expression
  );

  -- Create policy
  policy_name := format('update: %s.%s', schema_name, table_name);
  execute format(
    'drop policy if exists %I on %I.%I',
    policy_name,
    schema_name,
    table_name
  );
  execute format(
    $policy$
    create policy %I
    on %I.%I
    for update
    to authenticated
    using (%s)
    with check (%s)
    $policy$,
    policy_name,
    schema_name,
    table_name,
    using_expression,
    with_check_expression
  );
end;
$$
;
```

</details>

Other optimisations include:

- Use SQL rather than pl/pgSQL where possible
- Turn repeated function calls into subqueries so the query planner can cache the result, e.g. `user_id = auth.uid()` -> `user_id = (select auth.uid())`
- Try and use functions that take no arguments/take static arguments, so the result of the function is not dependent on the row you're checking. Ultimately Postgres just runs a massive C for-loop under the hood

The functions above return arrays of IDs for rows that the current user can create/read/update for this reason - the function only needs to be called once, rather than once for each row in the table.

Let me know if you have any questions :)

**Comment by probablykabari** [comment]
@OnCoreStudios No problem, glad that helped!

@tiniscule sure!

@isaacharrisholt Great points! I would note that a thing to remember is RLS functions run against the the _result_ rather than operating like a _where_ clause. So the first step in optimization happens before RLS comes into play when you are writing your query. SQL vs PLPGSQL matters less in this scenario because RLS functions are not being inlined. This `user_id = auth.uid() -> user_id = (select auth.uid())` makes no difference to the planner if `auth.uid()` is a `stable` function. In the example in your tweet, expanding the entire row to a function like `some_function(event.*)` rather than `some_function(id)` also makes a difference. 

Here's an example of how I use RLS functions in a scenario like yours. This is just an example based on the comment, not assuming your whole schema :) When I have nested relationships or relations ones that are many-to-many that I need RLS for, I flatten them with simpler id only returning functions. These are very fast and easy to compose and re-use. 

```sql
CREATE FUNCTION rls.current_provider_unit_ids() 
RETURNS SETOF uuid
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path TO 'pg_catalog', 'public', 'pg_temp'
AS $$
  select id from units where user_id = auth.uid();
$$;

CREATE POLICY view_owned ON units FOR SELECT USING ((id IN ( SELECT rls.current_provider_unit_ids() AS current_provider_unit_ids)));

CREATE POLICY view_owned ON property_valuation FOR SELECT USING ((unit_id IN ( SELECT rls.current_provider_unit_ids() AS current_provider_unit_ids)) or (some_permission() = "admin"));
```

**Comment by isaacharrisholt** [comment]
Ooh interesting!

I think this is effectively what we do - each function returns a set of ID arrays (for cases with composite primary keys, though this was set up before PostgREST supported having a third primary key column for many to many joins). I think the key optimisation was having these functions return the set of IDs rather than  taking in a given row and returning a boolean.
